### ISSUE TITLE
required input field not validating on pagination 

### ISSUE THREAD

**Issue by jansonMaharaj** [fullscreeninteractive/silverstripe-addressfinder#6]
Required attribute is not being applied to the input field when checked in the CMS. It gets ignored by user forms validation.

 **Context**
When creating a multi-page form with user define forms, all other required fields validated upon pagination except for the addressfinder field.

**Possible solution**
In AddressFinderField.php, in _constructor line 64. 
```
    public function __construct($name, $title = null, $value = null)
    {
        $this->addressField = new TextField("{$name}[Address]", $title);
        $this->addressField->setAttribute('autocomplete', 'off');
        $this->manualToggle = new HiddenField("{$name}[ManualAddress]");
        $this->manualFields = new FieldList();

add conditional statement if required is checked in CMS -  $this->addressField->setAttribute('required', 'required');
```
This feels like this should be apart of the expected behaviour of this module, rather then an extension.
This is a handy module, thanks for putting together.

Regards ,
Janson

**Comment by wilr** [comment]
@jansonMaharaj Thanks but perhaps try when you do your validator use RequiredFields::create(['AddressFieldName[Address]']) rather than 'AddressFieldName' as the required field and see if that works out of the box

**Comment by Uili-Simteau** [comment]
Hi,
Tried implementing this with a simple form, but the validator doesn't seem to call the Required() function as other FormFields do. Can you confirm a snippet that works for you? Here's mine:
```
use FullscreenInteractive\SilverStripe\AddressFinderField;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\TextField;
use SilverStripe\Forms\RequiredFields;
use SilverStripe\Forms\Form;
use SilverStripe\Forms\FormAction;

class PageController extends ContentController {
	private static $allowed_actions = [
        'HelloForm',
        'search'
    ];

  public function HelloForm() {
    $fields = new FieldList(
        // TextField::create('Name', 'Your Name'),
        $test = new AddressFinderField('AddressField')
    );

    $test->setMaxLength(2);


    $actions = new FieldList(
        FormAction::create('doSayHello')->setTitle('Say hello')
    );

    $required = RequiredFields::create(['AddressField[Address]']);

    $form = new Form($this, 'HelloForm', $fields, $actions, $required);
    $form->disableSecurityToken();

    return $form;
  }

  public function doSayHello($data, Form $form)
  {
    $form->sessionMessage('Hello ' . $data['Name'], 'success');

    return $this->redirectBack();
  }
```

**Comment by extravio** [comment]
Hi @wilr ,

Just a bit more info:
The validation on 'AddressField[Address]' is not kicking in because this field doesn't belong to the form. If we set the form on that child field, then things start working:
```
$fields = new FieldList($address = new AddressFinderField('AddressField'));
$actions = new FieldList(FormAction::create('submitAddress')->setTitle('Address'));
$required = RequiredFields::create(['AddressField', 'AddressField[Address]']);
$form = new Form($this, 'AddressForm', $fields, $actions, $required);
$address->getAddressField()->setForm($form);
return $form;
```
However, the validate function in AddressFinderField should then call
`parent::validate($validator);`
or execute the current logic depending on **manualToggle**
(The javascript should also be updated to remove the required attribute on 'AddressField[Address]' when entering the address manually)

What do yo uthink?

**Comment by Uili-Simteau** [comment]
HI @wilr, Any thoughts on the suggestions above?

Cheers,

Uili

**Comment by wilr** [comment]
@Uili-Simteau I've tested this on a simple form...
```
$fields = new FieldList(
            new TextField('FirstName', 'First name'),
            new TextField('Surname', 'Surname'),
            new EmailField('Email', 'Email'),
            new HiddenField('TakeUserToo', '', $nextStep),
            new AddressFinderField('Address'),
            $password = new PasswordField('Password', 'New Password'),
            new CheckboxField(
                'Terms',
                DBField::create_field(
                    'HTMLText',
                    sprintf(
                        'I agree to the <a href="%s" target="_blank">Privacy Policy</a> and <a href="%s" target="_blank">Terms of Conditions</a> for using our website, app and related services',
                        $privacy,
                        $terms
                    )
                )
            )
        );

        $password->setDescription('Make sure your password is secure. Want a random password? Try '. singleton(Member::class)->generatePassword());

        $actions = new FieldList(
            new FormAction('doRegister', "Register")
        );

        $validator = new RequiredFields(
            'FirstName',
            'Surname',
            'Email',
            'Password',
            'Terms',
            'DateOfBirth',
            'Address'
        );
```

`Address` is set as a required field, and I correctly get a warning.

![Screen Shot 2020-02-27 at 1 42 59 PM](https://user-images.githubusercontent.com/101629/75401459-1cecb580-5967-11ea-9ae5-762cf0f93bc9.png)

It doesn't set the `required` attribute via HTML5 since that would prevent the manual fields working but backend functionality appears to work fine.

**Comment by wilr** [comment]
This is on Silverstripe 4.5 with latest AddressFinder release (d6367b72189cae861f0c5b28d203595c54d96902).
